version: '3'
services:
  app:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    command: |
      sh -c "
        bundle install && \
        rm /app/myapp/tmp/pids/server.pid; bundle exec rails s -p 3000 -b 0.0.0.0
      "
    volumes:
      - ./myapp:/myapp
      - /app/myapp/vendor/bundle
      - /app/myapp/tmp
    ports:
      - "3000:3000"
    privileged: true
    tty: true
    stdin_open: true
    links:
      - db
    depends_on:
      - db

  db:
    image: "mariadb:latest"
    command: mysqld --character-set-server=utf8
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=oauth_tutorial_dev
      - MYSQL_ROOT_USER=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

