version: '3'
services:
  app:
    build:
      context: ./myapp
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./myapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
