default: &default
  adapter: <%= ENV['DB_ADAPTER'] ||= "mysql2" %>
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  username: root
  password: password
  host: db
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: dev
  database: oauth_tutorial_dev

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: oauth_tutorial_prod
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
